apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-demo-deployment
  labels:
    app: logging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging-container
        image: shudhoo/loggingg:v2
        ports:
        - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: logging-demo-service
  labels:
    app: logging-app-service
spec:
  type: NodePort
  selector:
    app: logging
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30007